### ISSUE TITLE
Errors for symbolic example and definite integral

### ISSUE THREAD

**Issue by emile-pelletier-gc** [SciML/SymbolicNumericIntegration.jl#96] opened 2024-05-29 14:20 UTC
**Describe the bug 🐞**

I cannot run anything in the examples code beyond the first example 
Did not work on Julia 1.9.3 
Installed Julia 1.10.3 (error persists).

I tried to run the example on the GitHub page: https://github.com/SciML/SymbolicNumericIntegration.jl with success only on the first integral but not the second.

`integrate(exp(a * x), x; symbolic = true)`

**Expected behavior**

I am trying to use symbolic integration, so expecting 

> exp(a * x) / a 
or this as per the example
> (exp(a * x) / a, 0, 0)

(in the error stacktrace, you will notice a line repeated many times, this was also the case in Julia 1.9.3 but there weren't as many repeated lines in 1.9.3)

**Minimal Reproducible Example 👇**

```
using Symbolics
using SymbolicNumericIntegration

@variables x a b

integrate(3x^3 + 2x - 5)
(x^2 + (3 // 4) * (x^4) - (5 // 1) * x, 0, 0)

integrate(exp(a * x), x; symbolic = true)
```

```julia

```

**Error & Stacktrace ⚠️**

```julia
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
Error from init_basis_matrix: UndefVarError(:a)
ERROR: TypeError: non-boolean (SymbolicUtils.BasicSymbolic{Bool}) used in boolean context
Stacktrace:
 [1] integrate_term(eq::SymbolicUtils.BasicSymbolic{…}, x::SymbolicUtils.BasicSymbolic{…}; kwargs::@Kwargs{…})
   @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\integral.jl:274
 [2] integrate_sum(eq::Num, x::SymbolicUtils.BasicSymbolic{…}; bypass::Bool, kwargs::@Kwargs{…})
   @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\integral.jl:171
 [3] integrate(eq::Num, x::Num; abstol::Float64, num_steps::Int64, num_trials::Int64, radius::Float64, show_basis::Bool, opt::DataDrivenSparse.STLSQ{…}, bypass::Bool, symbolic::Bool, max_basis::Int64, verbose::Bool, complex_plane::Bool, homotopy::Bool, use_optim::Bool, detailed::Bool)
   @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\integral.jl:102
 [4] top-level scope
   @ REPL[13]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `C:\Users\Emile\Desktop\CDP\codes 10\Project.toml`
  [78aadeae] SymbolicNumericIntegration v1.4.0
  [0c5d862f] Symbolics v5.28.0
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
Status `C:\Users\Emile\Desktop\CDP\codes 10\Manifest.toml`
  [47edcb42] ADTypes v1.2.1
  [1520ce14] AbstractTrees v0.4.5
  [7d9f7c33] Accessors v0.1.36
  [79e6a3ab] Adapt v4.0.4
  [66dad0bd] AliasTables v1.1.3
  [dce04be8] ArgCheck v2.3.0
  [ec485272] ArnoldiMethod v0.4.0
  [4fba245c] ArrayInterface v7.10.0
  [4c555306] ArrayLayouts v1.9.3
  [a9b6321e] Atomix v0.1.0
⌅ [198e06fe] BangBang v0.3.40
  [9718e550] Baselet v0.1.1
  [e2ed5e7c] Bijections v0.1.6
  [62783981] BitTwiddlingConvenienceFunctions v0.1.5
  [fa961155] CEnum v0.5.0
  [2a0fbf3d] CPUSummary v0.2.5
  [00ebfdb7] CSTParser v3.4.3
  [49dc2e85] Calculus v0.5.1
  [d360d2e6] ChainRulesCore v1.23.0
  [fb6a15b2] CloseOpenIntervals v0.1.12
  [861a8166] Combinatorics v1.0.2
  [a80b9123] CommonMark v0.8.12
  [38540f10] CommonSolve v0.2.4
  [bbf7d656] CommonSubexpressions v0.3.0
  [34da2185] Compat v4.15.0
  [b152e2b5] CompositeTypes v0.1.4
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.5.5
  [6add18c4] ContextVariablesX v0.1.3
  [adafc99b] CpuId v0.3.1
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [2445eb08] DataDrivenDiffEq v1.4.1
  [5b588203] DataDrivenSparse v0.1.2
  [82cc6244] DataInterpolations v5.0.0
  [864edb3b] DataStructures v0.18.20
  [e2d170a0] DataValueInterfaces v1.0.0
  [244e2a9f] DefineSingletons v0.1.2
  [8bb1440f] DelimitedFiles v1.9.1
  [2b5f629d] DiffEqBase v6.151.2
  [459566f4] DiffEqCallbacks v3.6.2
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
⌅ [a0c0ee7d] DifferentiationInterface v0.4.2
  [31c24e10] Distributions v0.25.108
  [ffbed154] DocStringExtensions v0.9.3
  [5b8099bc] DomainSets v0.7.14
  [fa6b7ba4] DualNumbers v0.6.8
  [7c1d4256] DynamicPolynomials v0.5.7
⌅ [06fc5a27] DynamicQuantities v0.13.2
  [4e289a0a] EnumX v1.0.4
  [f151be2c] EnzymeCore v0.7.3
  [d4d017d3] ExponentialUtilities v1.26.1
  [e2ba6199] ExprTools v0.1.10
  [cc61a311] FLoops v0.2.1
  [b9860ae5] FLoopsBase v0.1.1
⌃ [7034ab61] FastBroadcast v0.2.8
  [9aa1b823] FastClosures v0.3.2
  [29a986be] FastLapackInterface v2.0.4
  [1a297f60] FillArrays v1.11.0
  [64ca27bc] FindFirstFunctions v1.2.0
  [6a86dc24] FiniteDiff v2.23.1
  [1fa38f19] Format v1.3.7
  [f6369f11] ForwardDiff v0.10.36
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [d9f16b24] Functors v0.4.10
  [46192b85] GPUArraysCore v0.1.6
  [c145ed77] GenericSchur v0.5.4
  [c27321d9] Glob v1.3.1
  [86223c79] Graphs v1.11.0
  [3e5b6fbb] HostCPUFeatures v0.1.16
  [34004b35] HypergeometricFunctions v0.3.23
  [615f187c] IfElse v0.1.1
  [d25df0c9] Inflate v0.1.4
  [22cec73e] InitialValues v0.3.1
  [8197267c] IntervalSets v0.7.10
  [3587e190] InverseFunctions v0.1.14
  [92d709cd] IrrationalConstants v0.2.2
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.5.0
  [682c06a0] JSON v0.21.4
  [98e50ef6] JuliaFormatter v1.0.56
  [b14d175d] JuliaVariables v0.2.4
  [ccbc3e58] JumpProcesses v9.11.1
  [ef3ab10e] KLU v0.6.0
  [63c18a36] KernelAbstractions v0.9.19
  [ba0b0d4f] Krylov v0.9.6
  [929cbde3] LLVM v7.1.0
  [b964fa9f] LaTeXStrings v1.3.1
  [2ee39098] LabelledArrays v1.16.0
  [984bce1d] LambertW v0.4.6
  [23fbe1c1] Latexify v0.16.3
  [10f19ff3] LayoutPointers v0.1.15
  [5078a376] LazyArrays v2.0.2
  [d3d80556] LineSearches v7.2.0
  [7ed4a6bd] LinearSolve v2.30.1
  [2ab3a3ac] LogExpFunctions v0.3.27
  [bdcacae8] LoopVectorization v0.12.170
  [d8e11817] MLStyle v0.4.17
  [f1d291b0] MLUtils v0.4.4
  [1914dd2f] MacroTools v0.5.13
  [d125e4d3] ManualMemory v0.1.8
  [bb5d69b7] MaybeInplace v0.1.3
⌅ [128add7d] MicroCollections v0.1.4
  [e1d29d7a] Missings v1.2.0
  [961ee093] ModelingToolkit v9.15.0
  [46d2c3a1] MuladdMacro v0.2.4
  [102ac46a] MultivariatePolynomials v0.5.5
  [d8a4904e] MutableArithmetics v1.4.4
  [d41bc354] NLSolversBase v7.8.3
  [872c559c] NNlib v0.9.17
  [77ba4419] NaNMath v1.0.2
  [71a1bf82] NameResolution v0.1.5
  [8913a72c] NonlinearSolve v3.12.3
  [6fe1bfb0] OffsetArrays v1.14.0
  [bac558e1] OrderedCollections v1.6.3
  [1dea7af3] OrdinaryDiffEq v6.80.1
  [90014a1f] PDMats v0.11.31
  [65ce6f38] PackageExtensionCompat v1.0.2
  [d96e819e] Parameters v0.12.3
  [69de0a69] Parsers v2.8.1
  [e409e4f3] PoissonRandom v0.4.4
  [f517fe37] Polyester v0.7.14
  [1d0040c9] PolyesterWeave v0.2.1
  [d236fae5] PreallocationTools v0.4.21
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [8162dcfd] PrettyPrint v0.2.0
  [08abe8d2] PrettyTables v2.3.2
  [92933f4c] ProgressMeter v1.10.0
  [43287f4e] PtrArrays v1.2.0
  [1fd47b50] QuadGK v2.9.4
  [e6cf234a] RandomNumbers v1.5.3
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.19.0
  [f2c3362d] RecursiveFactorization v0.2.23
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.0
  [79098fc4] Rmath v0.7.1
  [7e49a35a] RuntimeGeneratedFunctions v0.5.13
  [94e857df] SIMDTypes v0.1.0
  [476501e8] SLEEFPirates v0.6.42
  [0bca4576] SciMLBase v2.39.0
  [c0aeaf25] SciMLOperators v0.3.8
  [53ae85a6] SciMLStructures v1.2.0
  [efcf1570] Setfield v1.1.1
  [605ecd9f] ShowCases v0.1.0
  [727e6d20] SimpleNonlinearSolve v1.9.0
  [699a6c99] SimpleTraits v0.9.4
  [ce78b400] SimpleUnPack v1.1.0
  [a2af1166] SortingAlgorithms v1.2.1
  [47a9eef4] SparseDiffTools v2.19.0
  [0a514795] SparseMatrixColorings v0.3.2
  [e56a9233] Sparspak v0.3.9
  [276daf66] SpecialFunctions v2.4.0
  [171d559e] SplittablesBase v0.1.15
  [aedffcd0] Static v0.8.10
  [0d7ed370] StaticArrayInterface v1.5.0
  [90137ffa] StaticArrays v1.9.4
  [1e83bf80] StaticArraysCore v1.4.2
  [82ae8749] StatsAPI v1.7.0
  [2913bbd2] StatsBase v0.34.3
  [4c63d2b9] StatsFuns v1.3.1
  [7792a7ef] StrideArraysCore v0.5.6
  [892a3eda] StringManipulation v0.3.4
  [2efcf032] SymbolicIndexingInterface v0.3.22
  [19f23fe9] SymbolicLimits v0.2.0
  [78aadeae] SymbolicNumericIntegration v1.4.0
⌅ [d1185830] SymbolicUtils v1.6.0
  [0c5d862f] Symbolics v5.28.0
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.11.1
  [8ea1fca8] TermInterface v0.4.1
  [8290d209] ThreadingUtilities v0.5.2
  [a759f4b9] TimerOutputs v0.5.24
  [0796e94c] Tokenize v0.5.29
⌃ [28d57a85] Transducers v0.4.80
  [d5829a12] TriangularSolve v0.2.0
  [410a4b4d] Tricks v0.1.8
  [781d530d] TruncatedStacktraces v1.4.0
  [5c2747f8] URIs v1.5.1
  [3a884ed6] UnPack v1.0.2
  [1986cc42] Unitful v1.20.0
  [a7c27f48] Unityper v0.1.6
  [013be700] UnsafeAtomics v0.2.1
  [d80eeb9a] UnsafeAtomicsLLVM v0.1.4
  [3d5dd08c] VectorizationBase v0.21.68
  [19fa3120] VertexSafeGraphs v0.2.0
  [1d5cc7b8] IntelOpenMP_jll v2024.1.0+0
  [dad2f222] LLVMExtra_jll v0.0.29+0
  [856f044c] MKL_jll v2024.1.0+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [f50d1b31] Rmath_jll v0.4.2+0
  [1317d2d5] oneTBB_jll v2021.12.0+0
  [0dad84c5] ArgTools v1.1.1
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [4af54fe1] LazyArtifacts
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.10.0
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays v1.10.0
  [10745b16] Statistics v1.10.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] LibCURL_jll v8.4.0+0
  [e37daf67] LibGit2_jll v1.6.4+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.2+1
  [14a3606d] MozillaCACerts_jll v2023.1.10
  [4536629a] OpenBLAS_jll v0.3.23+4
  [05823500] OpenLibm_jll v0.8.1+2
  [bea87d4a] SuiteSparse_jll v7.2.1+1
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.8.0+1
  [8e850ede] nghttp2_jll v1.52.0+1
  [3f19e933] p7zip_jll v17.4.0+2
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`
```

  - Output of `versioninfo()`

```julia
Julia Version 1.10.3
Commit 0b4590a550 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 4 × Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

**Additional context**

Definite integral doesn't work either
`integrate(x, (x, 0, 1))`

error:
```
ERROR: Sym doesn't have a operation or arguments!
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] error_sym()
    @ SymbolicUtils C:\Users\Emile\.julia\packages\SymbolicUtils\qyMYa\src\types.jl:82
  [3] operation(x::SymbolicUtils.BasicSymbolic{Real})
    @ SymbolicUtils C:\Users\Emile\.julia\packages\SymbolicUtils\qyMYa\src\types.jl:112
  [4] (::SymbolicUtils.Rewriters.Walk{…})(x::SymbolicUtils.BasicSymbolic{…})
    @ SymbolicUtils.Rewriters C:\Users\Emile\.julia\packages\SymbolicUtils\qyMYa\src\rewriters.jl:205
  [5] kernel(eq::SymbolicUtils.BasicSymbolic{Real})
    @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\rules.jl:95
  [6] generate_basis(eq::SymbolicNumericIntegration.ExprCache, x::SymbolicUtils.BasicSymbolic{Real}, try_kernel::Bool)
    @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\candidates.jl:15
  [7] integrate_term(eq::SymbolicUtils.BasicSymbolic{…}, x::SymbolicUtils.BasicSymbolic{…}; kwargs::@Kwargs{…})
    @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\integral.jl:246
  [8] integrate_sum(eq::Num, x::SymbolicUtils.BasicSymbolic{…}; bypass::Bool, kwargs::@Kwargs{…})
    @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\integral.jl:171
  [9] integrate(eq::Num, x::Num; abstol::Float64, num_steps::Int64, num_trials::Int64, radius::Float64, show_basis::Bool, opt::DataDrivenSparse.STLSQ{…}, bypass::Bool, symbolic::Bool, max_basis::Int64, verbose::Bool, complex_plane::Bool, homotopy::Bool, use_optim::Bool, detailed::Bool)
    @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\integral.jl:102
 [10] integrate(eq::Num, x::Num)
    @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\integral.jl:58
 [11] integrate(eq::Num, xx::Tuple{Num, Int64, Int64}; kwargs::@Kwargs{})
    @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\integral.jl:121
 [12] integrate(eq::Num, xx::Tuple{Num, Int64, Int64})
    @ SymbolicNumericIntegration C:\Users\Emile\.julia\packages\SymbolicNumericIntegration\yuCPz\src\integral.jl:119
 [13] top-level scope
    @ REPL[27]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**Comment by emile-pelletier-gc** [comment] 2024-05-29 16:56
it appears even the first example won't run:
`integrate(3x^3 + 2x - 5) ` 
gives the error as above beginning: 
`ERROR: Sym doesn't have a operation or arguments!`

I had skipped straight to the second example which I was hoping would run after changing over from 1.9.3 to 1.10.3. When that produced the same error, I wanted to check the definite integral but got this, 
```
integrate(x^2, (x, 0, 1))
ERROR: Failed to apply rule Ω((~(x::is_linear_poly)) ^ ~(k::is_pos_int)) => (~x) ^ ~k on expression Ω(x^2)
```

**Comment by karlwessel** [comment] 2024-08-20 05:19
Version 1.4 is the last version that works for me. I guess the newer versions of Symbolics or SymbolicUtils broke compatibility.

**Comment by ChrisRackauckas** [comment] 2024-08-20 11:44
We had a hiccup during the previous symbolic release. It should be fixed now. I just confirmed locally.

**Closed by ChrisRackauckas** 2024-08-20 11:44 UTC
Labels: bug

**Comment by karlwessel** [comment] 2024-08-20 12:05
Thank you! It works now, although running the test cases now takes twice as long and there are a lot of deprecation warnings.

**Comment by ChrisRackauckas** [comment] 2024-08-20 12:14
I plan to be poking at those over the next week or so in https://github.com/SciML/SymbolicNumericIntegration.jl/pull/98, any help to root them out would be great.
